from __future__ import annotations

DEFAULT_LOG_WORLD_SIZE = 160

# Simulation constants
DEFAULT_MAX_TIME = 2000000
DEFAULT_NODES = 100
DEFAULT_PEER_TIMEOUT = 500.0
CLIENT_TIMEOUT_MULTIPLIER = 6
DEFAULT_CLIENT_TIMEOUT = DEFAULT_PEER_TIMEOUT * CLIENT_TIMEOUT_MULTIPLIER
DEFAULT_MAX_VALUE = 10 ** 9

DEFAULT_QUEUE_CAPACITY = 100
DEFAULT_MEAN_SERVICE_TIME = 5
DEFAULT_NUMBER_OF_SERVERS = 1

DEFAULT_ALPHA = 3
DEFAULT_K = 5

# Chord stabilize and update periods
DEFAULT_UPDATE_PERIOD_MIN = 150000
DEFAULT_UPDATE_PERIOD_STDDEV = 5000
DEFAULT_UPDATE_PERIOD_MEAN = 200000
DEFAULT_STABILIZE_PERIOD_MIN = 3000
DEFAULT_STABILIZE_PERIOD_STDDEV = 100
DEFAULT_STABILIZE_PERIOD_MEAN = 5000

# Kademlia
DEFAULT_KAD_FIND_NODE_TIMEOUT = DEFAULT_PEER_TIMEOUT

# utility
DEFAULT_EXT = "pdf"
DEFAULT_LOGGING = "ERROR"
DEFAULT_PLOT = False

# Simulation parameters
DEFAULT_SEED = 420
DEFAULT_N_KEYS = 10 ** 3
DEFAULT_CLIENT_RATE = 5
DEFAULT_JOINLAMBDA1 = 10
DEFAULT_JOINLAMBDA2 = 5
DEFAULT_JOIN_P = 0.3
DEFAULT_JOINRATE = 1
DEFAULT_CRASHMEAN = 10
DEFAULT_CRASHVARIANCE = 5
DEFAULT_CRASHRATE = 1
