from __future__ import annotations

WORLD_SIZE = 160

# Simulation constants
DEFAULT_MAX_TIME = 200000
DEFAULT_NODES = 100
DEFAULT_PEER_TIMEOUT = 500.0
CLIENT_TIMEOUT_MULTIPLIER = 6
DEFAULT_QUEUE_CAPACITY = 100
DEFAULT_ALPHA = 3
DEFAULT_K = 5

# utility
DEFAULT_EXT = "pdf"
DEFAULT_LOGGING = "ERROR"
DEFAULT_PLOT = False

# Simulation parameters
DEFAULT_SEED = 420
DEFAULT_N_KEYS = 10 ** 3
DEFAULT_CLIENT_RATE = 5
DEFAULT_JOINLAMBDA1 = 10
DEFAULT_JOINLAMBDA2 = 5
DEFAULT_JOINRATE = 1
DEFAULT_CRASHMEAN = 10
DEFAULT_CRASHVARIANCE = 5
DEFAULT_CRASHRATE = 1
